In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
import scipy

In [ ]:
class neuralNetwork:
    def __init__(self,inputnodes,hiddennodes,outputnodes,learning_rate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.lr = learning_rate

        self.wih = np.random.normal(0.0,pow(self.hnodes,-0.5),(self.hnodes,self.inodes))
        self.who = np.random.normal(0.0,pow(self.onodes,-0.5,(self.onodes,self.hnodes)))

        self.activation_function = lambda x: scipy.special.expit(x)

    def train(self,input_list,target_list):
        inputs = np.array(input_list,ndmin=2).T
        targets = np.array(target_list,ndmin=2).T

        hidden_inputs = np.dot(self.wih,inputs)
        hidden_outputs = self.activation_function(hidden_inputs)

        final_inputs = np.dot(self.who,hidden_inputs)
        final_outputs = self.activation_function(final_inputs)

        output_errors = targets - final_outputs 
        hidden_errors = np.dot(self.who.T,output_errors)

        self.who += self.lr*np.dot((output_errors*final_outputs*(1-final_outputs)),np.transpose(hidden_inputs))
        self.wih += self.lr*np.dot((hidden_errors*hidden_outputs*(1-hidden_outputs)),np.transpose(inputs))


    def query(self,inputs_list):
        inputs = np.array(inputs_list,ndmin=2).T

        hidden_inputs = np.dot(self.wih,inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = np.dot(self.who,hidden_outputs)
        final_outputs = self.activation_function(final_inputs)

        return final_outputs
    


In [8]:
class NN:
    def __init__(self,inputnodes,hiddennodes,outputnodes,learning_rate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.lr = learning_rate

        self.wih = np.random.normal(0.0,pow(self.hnodes,-0.5),(self.hnodes,self.inodes))
        self.bih = 0
    
        self.who = np.random.normal(0.0,pow(self.onodes,-0.5),(self.onodes,self.hnodes))
        self.bho = 0

    def forward(self,X):
        hidden_inputs = np.dot(self.wih,X)+self.bih
        hidden_outputs = self.activation(hidden_inputs)

        final_inputs = np.dot(self.who,hidden_outputs)+self.bih
        final_outputs = self.activation(final_inputs)

        return final_outputs
    
    def


    def activation(self,z):
        return 1/(1+(np.exp(-z)))
    



[[-0.17285374  1.03259244  0.25727131]
 [ 0.08060507 -0.07130536  0.07850078]
 [-1.02395854  0.14453169  0.23607477]
 [-0.13565411 -0.03891316  0.36814651]
 [ 0.4193057  -0.13284728 -0.37040514]]

[[-0.63251063 -0.10085104  0.9573909   0.70906453 -1.39634968]
 [-0.4700948   0.89911411  0.3814442  -0.13710531 -0.46109094]]
